# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
builds:
  - main: ./cmd/pigeon
    binary: pigeon
    tags:
      - netgo
      - gcc
      - ledger
    ldflags:
      - -s -w
      - -X github.com/palomachain/pigeon/app.version={{ .Tag }}
      - -X github.com/palomachain/pigeon/app.commit={{ .FullCommit }}
      - -extldflags "-Wl,--allow-multiple-definition"
    goos:
      - linux
    goarch:
      - amd64

archives:
  - name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else }}{{ .Arch }}{{ end }}
    files:
      - LICENSE
      - README.md

checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^test:'
      - '^third_party_proto:'
      - '^scripts:'
      - '^docs:'
