// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	time "time"

	mock "github.com/stretchr/testify/mock"
)

// Time is an autogenerated mock type for the Time type
type Time struct {
	mock.Mock
}

// Now provides a mock function with given fields:
func (_m *Time) Now() time.Time {
	ret := _m.Called()

	var r0 time.Time
	if rf, ok := ret.Get(0).(func() time.Time); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(time.Time)
	}

	return r0
}

type mockConstructorTestingTNewTime interface {
	mock.TestingT
	Cleanup(func())
}

// NewTime creates a new instance of Time. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewTime(t mockConstructorTestingTNewTime) *Time {
	mock := &Time{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
