// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: paloma/valset/query.proto

package types

import (
	context "context"
	fmt "fmt"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/cosmos-sdk/types/query"
	_ "github.com/gogo/protobuf/gogoproto"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	github_com_gogo_protobuf_types "github.com/gogo/protobuf/types"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	io "io"
	math "math"
	math_bits "math/bits"
	time "time"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// QueryParamsRequest is request type for the Query/Params RPC method.
type QueryParamsRequest struct {
}

func (m *QueryParamsRequest) Reset()         { *m = QueryParamsRequest{} }
func (m *QueryParamsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryParamsRequest) ProtoMessage()    {}
func (*QueryParamsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b7cb1d6eb17975b, []int{0}
}
func (m *QueryParamsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsRequest.Merge(m, src)
}
func (m *QueryParamsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsRequest proto.InternalMessageInfo

// QueryParamsResponse is response type for the Query/Params RPC method.
type QueryParamsResponse struct {
	// params holds all the parameters of this module.
	Params Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
}

func (m *QueryParamsResponse) Reset()         { *m = QueryParamsResponse{} }
func (m *QueryParamsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryParamsResponse) ProtoMessage()    {}
func (*QueryParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b7cb1d6eb17975b, []int{1}
}
func (m *QueryParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsResponse.Merge(m, src)
}
func (m *QueryParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsResponse proto.InternalMessageInfo

func (m *QueryParamsResponse) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

type QueryValidatorInfoRequest struct {
	ValAddr string `protobuf:"bytes,1,opt,name=valAddr,proto3" json:"valAddr,omitempty"`
}

func (m *QueryValidatorInfoRequest) Reset()         { *m = QueryValidatorInfoRequest{} }
func (m *QueryValidatorInfoRequest) String() string { return proto.CompactTextString(m) }
func (*QueryValidatorInfoRequest) ProtoMessage()    {}
func (*QueryValidatorInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b7cb1d6eb17975b, []int{2}
}
func (m *QueryValidatorInfoRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryValidatorInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryValidatorInfoRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryValidatorInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryValidatorInfoRequest.Merge(m, src)
}
func (m *QueryValidatorInfoRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryValidatorInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryValidatorInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryValidatorInfoRequest proto.InternalMessageInfo

func (m *QueryValidatorInfoRequest) GetValAddr() string {
	if m != nil {
		return m.ValAddr
	}
	return ""
}

type QueryValidatorInfoResponse struct {
	ChainInfos []*ExternalChainInfo `protobuf:"bytes,1,rep,name=chainInfos,proto3" json:"chainInfos,omitempty"`
}

func (m *QueryValidatorInfoResponse) Reset()         { *m = QueryValidatorInfoResponse{} }
func (m *QueryValidatorInfoResponse) String() string { return proto.CompactTextString(m) }
func (*QueryValidatorInfoResponse) ProtoMessage()    {}
func (*QueryValidatorInfoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b7cb1d6eb17975b, []int{3}
}
func (m *QueryValidatorInfoResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryValidatorInfoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryValidatorInfoResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryValidatorInfoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryValidatorInfoResponse.Merge(m, src)
}
func (m *QueryValidatorInfoResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryValidatorInfoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryValidatorInfoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryValidatorInfoResponse proto.InternalMessageInfo

func (m *QueryValidatorInfoResponse) GetChainInfos() []*ExternalChainInfo {
	if m != nil {
		return m.ChainInfos
	}
	return nil
}

type QueryGetSnapshotByIDRequest struct {
	SnapshotId uint64 `protobuf:"varint,1,opt,name=snapshotId,proto3" json:"snapshotId,omitempty"`
}

func (m *QueryGetSnapshotByIDRequest) Reset()         { *m = QueryGetSnapshotByIDRequest{} }
func (m *QueryGetSnapshotByIDRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetSnapshotByIDRequest) ProtoMessage()    {}
func (*QueryGetSnapshotByIDRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b7cb1d6eb17975b, []int{4}
}
func (m *QueryGetSnapshotByIDRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetSnapshotByIDRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetSnapshotByIDRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetSnapshotByIDRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetSnapshotByIDRequest.Merge(m, src)
}
func (m *QueryGetSnapshotByIDRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetSnapshotByIDRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetSnapshotByIDRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetSnapshotByIDRequest proto.InternalMessageInfo

func (m *QueryGetSnapshotByIDRequest) GetSnapshotId() uint64 {
	if m != nil {
		return m.SnapshotId
	}
	return 0
}

type QueryGetSnapshotByIDResponse struct {
	Snapshot *Snapshot `protobuf:"bytes,1,opt,name=snapshot,proto3" json:"snapshot,omitempty"`
}

func (m *QueryGetSnapshotByIDResponse) Reset()         { *m = QueryGetSnapshotByIDResponse{} }
func (m *QueryGetSnapshotByIDResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetSnapshotByIDResponse) ProtoMessage()    {}
func (*QueryGetSnapshotByIDResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b7cb1d6eb17975b, []int{5}
}
func (m *QueryGetSnapshotByIDResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetSnapshotByIDResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetSnapshotByIDResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetSnapshotByIDResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetSnapshotByIDResponse.Merge(m, src)
}
func (m *QueryGetSnapshotByIDResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetSnapshotByIDResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetSnapshotByIDResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetSnapshotByIDResponse proto.InternalMessageInfo

func (m *QueryGetSnapshotByIDResponse) GetSnapshot() *Snapshot {
	if m != nil {
		return m.Snapshot
	}
	return nil
}

type QueryGetValidatorAliveUntilRequest struct {
	ValAddress github_com_cosmos_cosmos_sdk_types.ValAddress `protobuf:"bytes,1,opt,name=valAddress,proto3,casttype=github.com/cosmos/cosmos-sdk/types.ValAddress" json:"valAddress,omitempty"`
}

func (m *QueryGetValidatorAliveUntilRequest) Reset()         { *m = QueryGetValidatorAliveUntilRequest{} }
func (m *QueryGetValidatorAliveUntilRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetValidatorAliveUntilRequest) ProtoMessage()    {}
func (*QueryGetValidatorAliveUntilRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b7cb1d6eb17975b, []int{6}
}
func (m *QueryGetValidatorAliveUntilRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetValidatorAliveUntilRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetValidatorAliveUntilRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetValidatorAliveUntilRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetValidatorAliveUntilRequest.Merge(m, src)
}
func (m *QueryGetValidatorAliveUntilRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetValidatorAliveUntilRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetValidatorAliveUntilRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetValidatorAliveUntilRequest proto.InternalMessageInfo

func (m *QueryGetValidatorAliveUntilRequest) GetValAddress() github_com_cosmos_cosmos_sdk_types.ValAddress {
	if m != nil {
		return m.ValAddress
	}
	return nil
}

type QueryGetValidatorAliveUntilResponse struct {
	AliveUntil time.Time `protobuf:"bytes,1,opt,name=aliveUntil,proto3,stdtime" json:"aliveUntil"`
}

func (m *QueryGetValidatorAliveUntilResponse) Reset()         { *m = QueryGetValidatorAliveUntilResponse{} }
func (m *QueryGetValidatorAliveUntilResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetValidatorAliveUntilResponse) ProtoMessage()    {}
func (*QueryGetValidatorAliveUntilResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b7cb1d6eb17975b, []int{7}
}
func (m *QueryGetValidatorAliveUntilResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetValidatorAliveUntilResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetValidatorAliveUntilResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetValidatorAliveUntilResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetValidatorAliveUntilResponse.Merge(m, src)
}
func (m *QueryGetValidatorAliveUntilResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetValidatorAliveUntilResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetValidatorAliveUntilResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetValidatorAliveUntilResponse proto.InternalMessageInfo

func (m *QueryGetValidatorAliveUntilResponse) GetAliveUntil() time.Time {
	if m != nil {
		return m.AliveUntil
	}
	return time.Time{}
}

func init() {
	proto.RegisterType((*QueryParamsRequest)(nil), "volumefi.paloma.valset.QueryParamsRequest")
	proto.RegisterType((*QueryParamsResponse)(nil), "volumefi.paloma.valset.QueryParamsResponse")
	proto.RegisterType((*QueryValidatorInfoRequest)(nil), "volumefi.paloma.valset.QueryValidatorInfoRequest")
	proto.RegisterType((*QueryValidatorInfoResponse)(nil), "volumefi.paloma.valset.QueryValidatorInfoResponse")
	proto.RegisterType((*QueryGetSnapshotByIDRequest)(nil), "volumefi.paloma.valset.QueryGetSnapshotByIDRequest")
	proto.RegisterType((*QueryGetSnapshotByIDResponse)(nil), "volumefi.paloma.valset.QueryGetSnapshotByIDResponse")
	proto.RegisterType((*QueryGetValidatorAliveUntilRequest)(nil), "volumefi.paloma.valset.QueryGetValidatorAliveUntilRequest")
	proto.RegisterType((*QueryGetValidatorAliveUntilResponse)(nil), "volumefi.paloma.valset.QueryGetValidatorAliveUntilResponse")
}

func init() { proto.RegisterFile("paloma/valset/query.proto", fileDescriptor_0b7cb1d6eb17975b) }

var fileDescriptor_0b7cb1d6eb17975b = []byte{
	// 680 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x93, 0x4f, 0x4f, 0x13, 0x4f,
	0x18, 0xc7, 0xbb, 0xbf, 0x1f, 0x20, 0x0e, 0x1a, 0x93, 0x01, 0x09, 0xac, 0x64, 0x4b, 0xd6, 0xc4,
	0x20, 0xca, 0x8e, 0x2d, 0x68, 0x0c, 0xe2, 0x81, 0x8a, 0x9a, 0xde, 0x64, 0x51, 0x0e, 0xc6, 0xa4,
	0x99, 0xd2, 0xe9, 0x32, 0x61, 0x77, 0x67, 0xe9, 0x4c, 0x2b, 0x0d, 0xe1, 0xe2, 0xcd, 0x1b, 0x89,
	0x6f, 0xc4, 0x97, 0xe0, 0x91, 0x9b, 0x24, 0x5e, 0x4c, 0x4c, 0xd0, 0x80, 0xaf, 0xc2, 0x93, 0xd9,
	0xf9, 0x53, 0x0a, 0x6e, 0x41, 0x3c, 0xc1, 0x3e, 0x7d, 0xbe, 0xcf, 0xf3, 0x79, 0x9e, 0xf9, 0x3e,
	0x60, 0x3c, 0xc1, 0x21, 0x8b, 0x30, 0x6a, 0xe1, 0x90, 0x13, 0x81, 0x36, 0x9b, 0xa4, 0xd1, 0xf6,
	0x92, 0x06, 0x13, 0x0c, 0x8e, 0xb6, 0x58, 0xd8, 0x8c, 0x48, 0x9d, 0x7a, 0x2a, 0xc7, 0x53, 0x39,
	0xf6, 0x48, 0xc0, 0x02, 0x26, 0x53, 0x50, 0xfa, 0x9f, 0xca, 0xb6, 0x27, 0x02, 0xc6, 0x82, 0x90,
	0x20, 0x9c, 0x50, 0x84, 0xe3, 0x98, 0x09, 0x2c, 0x28, 0x8b, 0xb9, 0xfe, 0x75, 0x7a, 0x8d, 0xf1,
	0x88, 0x71, 0x54, 0xc5, 0x9c, 0xa8, 0x26, 0xa8, 0x55, 0xa8, 0x12, 0x81, 0x0b, 0x28, 0xc1, 0x01,
	0x8d, 0x65, 0xb2, 0xce, 0x1d, 0xd6, 0x2c, 0x09, 0x6e, 0xe0, 0xc8, 0x14, 0xb8, 0xae, 0x83, 0x3c,
	0xc6, 0x09, 0x5f, 0x67, 0x42, 0x87, 0xf3, 0xba, 0xab, 0xfc, 0xaa, 0x36, 0xeb, 0x48, 0xd0, 0x88,
	0x70, 0x81, 0xa3, 0x44, 0x25, 0xb8, 0x23, 0x00, 0x2e, 0xa7, 0xed, 0x5e, 0xc8, 0x62, 0x3e, 0xd9,
	0x6c, 0x12, 0x2e, 0xdc, 0x15, 0x30, 0x7c, 0x22, 0xca, 0x13, 0x16, 0x73, 0x02, 0x17, 0xc0, 0x80,
	0x6a, 0x3a, 0x66, 0x4d, 0x5a, 0x53, 0x43, 0x45, 0xc7, 0xcb, 0x5e, 0x81, 0xa7, 0x74, 0xa5, 0xbe,
	0xbd, 0x83, 0x7c, 0xce, 0xd7, 0x1a, 0xf7, 0x3e, 0x18, 0x97, 0x45, 0x57, 0x71, 0x48, 0x6b, 0x58,
	0xb0, 0x46, 0x39, 0xae, 0x33, 0xdd, 0x11, 0x8e, 0x81, 0x4b, 0x2d, 0x1c, 0x2e, 0xd6, 0x6a, 0x0d,
	0x59, 0xfb, 0xb2, 0x6f, 0x3e, 0xdd, 0x00, 0xd8, 0x59, 0x32, 0x8d, 0x54, 0x06, 0x60, 0x6d, 0x1d,
	0xd3, 0x38, 0x0d, 0xa6, 0x58, 0xff, 0x4f, 0x0d, 0x15, 0x6f, 0xf7, 0xc2, 0x7a, 0xba, 0x25, 0x48,
	0x23, 0xc6, 0xe1, 0x13, 0xa3, 0xf0, 0xbb, 0xc4, 0xee, 0x63, 0x70, 0x43, 0x36, 0x7a, 0x4e, 0xc4,
	0x8a, 0xde, 0x62, 0xa9, 0x5d, 0x5e, 0x32, 0x84, 0x0e, 0x00, 0x66, 0xb9, 0xe5, 0x9a, 0x84, 0xec,
	0xf3, 0xbb, 0x22, 0xee, 0x1b, 0x30, 0x91, 0x2d, 0xef, 0x2c, 0x6f, 0xd0, 0x64, 0xeb, 0xf5, 0x4d,
	0xf6, 0xe2, 0x34, 0x7a, 0xbf, 0xa3, 0x70, 0xdf, 0x02, 0xd7, 0x54, 0xef, 0x2c, 0x62, 0x31, 0xa4,
	0x2d, 0xf2, 0x2a, 0x16, 0x34, 0x34, 0x8c, 0xcb, 0x00, 0xe8, 0xb5, 0x11, 0xae, 0x1e, 0xe9, 0x4a,
	0xa9, 0xf0, 0xeb, 0x20, 0x3f, 0x13, 0x50, 0xb1, 0xde, 0xac, 0x7a, 0x6b, 0x2c, 0x42, 0xda, 0x69,
	0xea, 0xcf, 0x0c, 0xaf, 0x6d, 0x20, 0xd1, 0x4e, 0x08, 0xf7, 0x56, 0x3b, 0x42, 0xbf, 0xab, 0x88,
	0xbb, 0x01, 0x6e, 0x9e, 0xd9, 0x58, 0x4f, 0xb7, 0x04, 0x00, 0xee, 0x44, 0xf5, 0x7c, 0xb6, 0xa7,
	0xdc, 0xe7, 0x19, 0xf7, 0x79, 0x2f, 0x8d, 0xfb, 0x4a, 0x83, 0xa9, 0x35, 0x76, 0xbf, 0xe7, 0x2d,
	0xbf, 0x4b, 0x57, 0xfc, 0xd6, 0x0f, 0xfa, 0x65, 0x37, 0xf8, 0xde, 0x02, 0x03, 0xca, 0x45, 0x70,
	0xba, 0xd7, 0x9a, 0xfe, 0x34, 0xae, 0x7d, 0xe7, 0xaf, 0x72, 0x15, 0xb3, 0x7b, 0xeb, 0xdd, 0x97,
	0x9f, 0x1f, 0xfe, 0x9b, 0x84, 0x0e, 0x32, 0x22, 0x74, 0xf2, 0xda, 0x95, 0x71, 0xe1, 0x47, 0x0b,
	0x5c, 0x3d, 0xe1, 0x3e, 0x58, 0x38, 0xb3, 0x4d, 0x96, 0xc1, 0xed, 0xe2, 0x45, 0x24, 0x1a, 0xf0,
	0xa1, 0x04, 0x2c, 0xc2, 0x7b, 0xbd, 0x00, 0x5b, 0x46, 0x56, 0xa1, 0x71, 0x9d, 0xa1, 0x6d, 0xfd,
	0x6e, 0x3b, 0xf0, 0x93, 0x05, 0xae, 0x9d, 0x32, 0x22, 0x9c, 0x3d, 0x93, 0x20, 0xdb, 0xf5, 0xf6,
	0xdc, 0xc5, 0x44, 0x1a, 0xbc, 0x24, 0xc1, 0x17, 0xe0, 0xbc, 0xe6, 0x95, 0x57, 0x76, 0x8a, 0x3d,
	0x20, 0xa2, 0x62, 0xec, 0x5d, 0xa9, 0xb6, 0x2b, 0xb4, 0x86, 0xb6, 0x8f, 0xcf, 0x69, 0x07, 0x7e,
	0xb6, 0xc0, 0x68, 0xb6, 0xe9, 0xe0, 0xfc, 0x79, 0x50, 0xbd, 0x4f, 0xc4, 0x7e, 0xf4, 0x4f, 0x5a,
	0x3d, 0xd7, 0x82, 0x9c, 0xeb, 0x01, 0x9c, 0x3b, 0x67, 0xae, 0xe3, 0x77, 0x91, 0xe6, 0xae, 0x34,
	0xd3, 0x2a, 0xa5, 0x67, 0x7b, 0x87, 0x8e, 0xb5, 0x7f, 0xe8, 0x58, 0x3f, 0x0e, 0x1d, 0x6b, 0xf7,
	0xc8, 0xc9, 0xed, 0x1f, 0x39, 0xb9, 0xaf, 0x47, 0x4e, 0xee, 0xf5, 0xdd, 0xae, 0xfb, 0xcc, 0xa8,
	0xbc, 0x65, 0x6a, 0xcb, 0x4b, 0xad, 0x0e, 0xc8, 0x7b, 0x9a, 0xfd, 0x1d, 0x00, 0x00, 0xff, 0xff,
	0x55, 0x13, 0xff, 0xfb, 0x9c, 0x06, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Parameters queries the parameters of the module.
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
	// Queries a list of ValidatorInfo items.
	ValidatorInfo(ctx context.Context, in *QueryValidatorInfoRequest, opts ...grpc.CallOption) (*QueryValidatorInfoResponse, error)
	// Queries a list of GetSnapshotByID items.
	GetSnapshotByID(ctx context.Context, in *QueryGetSnapshotByIDRequest, opts ...grpc.CallOption) (*QueryGetSnapshotByIDResponse, error)
	// Queries a list of GetValidatorAliveUntil items.
	GetValidatorAliveUntil(ctx context.Context, in *QueryGetValidatorAliveUntilRequest, opts ...grpc.CallOption) (*QueryGetValidatorAliveUntilResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, "/volumefi.paloma.valset.Query/Params", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) ValidatorInfo(ctx context.Context, in *QueryValidatorInfoRequest, opts ...grpc.CallOption) (*QueryValidatorInfoResponse, error) {
	out := new(QueryValidatorInfoResponse)
	err := c.cc.Invoke(ctx, "/volumefi.paloma.valset.Query/ValidatorInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) GetSnapshotByID(ctx context.Context, in *QueryGetSnapshotByIDRequest, opts ...grpc.CallOption) (*QueryGetSnapshotByIDResponse, error) {
	out := new(QueryGetSnapshotByIDResponse)
	err := c.cc.Invoke(ctx, "/volumefi.paloma.valset.Query/GetSnapshotByID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) GetValidatorAliveUntil(ctx context.Context, in *QueryGetValidatorAliveUntilRequest, opts ...grpc.CallOption) (*QueryGetValidatorAliveUntilResponse, error) {
	out := new(QueryGetValidatorAliveUntilResponse)
	err := c.cc.Invoke(ctx, "/volumefi.paloma.valset.Query/GetValidatorAliveUntil", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Parameters queries the parameters of the module.
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
	// Queries a list of ValidatorInfo items.
	ValidatorInfo(context.Context, *QueryValidatorInfoRequest) (*QueryValidatorInfoResponse, error)
	// Queries a list of GetSnapshotByID items.
	GetSnapshotByID(context.Context, *QueryGetSnapshotByIDRequest) (*QueryGetSnapshotByIDResponse, error)
	// Queries a list of GetValidatorAliveUntil items.
	GetValidatorAliveUntil(context.Context, *QueryGetValidatorAliveUntilRequest) (*QueryGetValidatorAliveUntilResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Params(ctx context.Context, req *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Params not implemented")
}
func (*UnimplementedQueryServer) ValidatorInfo(ctx context.Context, req *QueryValidatorInfoRequest) (*QueryValidatorInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ValidatorInfo not implemented")
}
func (*UnimplementedQueryServer) GetSnapshotByID(ctx context.Context, req *QueryGetSnapshotByIDRequest) (*QueryGetSnapshotByIDResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSnapshotByID not implemented")
}
func (*UnimplementedQueryServer) GetValidatorAliveUntil(ctx context.Context, req *QueryGetValidatorAliveUntilRequest) (*QueryGetValidatorAliveUntilResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetValidatorAliveUntil not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/volumefi.paloma.valset.Query/Params",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_ValidatorInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryValidatorInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).ValidatorInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/volumefi.paloma.valset.Query/ValidatorInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).ValidatorInfo(ctx, req.(*QueryValidatorInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_GetSnapshotByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetSnapshotByIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).GetSnapshotByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/volumefi.paloma.valset.Query/GetSnapshotByID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).GetSnapshotByID(ctx, req.(*QueryGetSnapshotByIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_GetValidatorAliveUntil_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetValidatorAliveUntilRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).GetValidatorAliveUntil(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/volumefi.paloma.valset.Query/GetValidatorAliveUntil",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).GetValidatorAliveUntil(ctx, req.(*QueryGetValidatorAliveUntilRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "volumefi.paloma.valset.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
		{
			MethodName: "ValidatorInfo",
			Handler:    _Query_ValidatorInfo_Handler,
		},
		{
			MethodName: "GetSnapshotByID",
			Handler:    _Query_GetSnapshotByID_Handler,
		},
		{
			MethodName: "GetValidatorAliveUntil",
			Handler:    _Query_GetValidatorAliveUntil_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "paloma/valset/query.proto",
}

func (m *QueryParamsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryValidatorInfoRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryValidatorInfoRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryValidatorInfoRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.ValAddr) > 0 {
		i -= len(m.ValAddr)
		copy(dAtA[i:], m.ValAddr)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.ValAddr)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryValidatorInfoResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryValidatorInfoResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryValidatorInfoResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.ChainInfos) > 0 {
		for iNdEx := len(m.ChainInfos) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.ChainInfos[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetSnapshotByIDRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetSnapshotByIDRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetSnapshotByIDRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.SnapshotId != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.SnapshotId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetSnapshotByIDResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetSnapshotByIDResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetSnapshotByIDResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Snapshot != nil {
		{
			size, err := m.Snapshot.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetValidatorAliveUntilRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetValidatorAliveUntilRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetValidatorAliveUntilRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.ValAddress) > 0 {
		i -= len(m.ValAddress)
		copy(dAtA[i:], m.ValAddress)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.ValAddress)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetValidatorAliveUntilResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetValidatorAliveUntilResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetValidatorAliveUntilResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	n3, err3 := github_com_gogo_protobuf_types.StdTimeMarshalTo(m.AliveUntil, dAtA[i-github_com_gogo_protobuf_types.SizeOfStdTime(m.AliveUntil):])
	if err3 != nil {
		return 0, err3
	}
	i -= n3
	i = encodeVarintQuery(dAtA, i, uint64(n3))
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryParamsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryValidatorInfoRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ValAddr)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryValidatorInfoResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.ChainInfos) > 0 {
		for _, e := range m.ChainInfos {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	return n
}

func (m *QueryGetSnapshotByIDRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.SnapshotId != 0 {
		n += 1 + sovQuery(uint64(m.SnapshotId))
	}
	return n
}

func (m *QueryGetSnapshotByIDResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Snapshot != nil {
		l = m.Snapshot.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetValidatorAliveUntilRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ValAddress)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetValidatorAliveUntilResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = github_com_gogo_protobuf_types.SizeOfStdTime(m.AliveUntil)
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryParamsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryValidatorInfoRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryValidatorInfoRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryValidatorInfoRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ValAddr", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ValAddr = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryValidatorInfoResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryValidatorInfoResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryValidatorInfoResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ChainInfos", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ChainInfos = append(m.ChainInfos, &ExternalChainInfo{})
			if err := m.ChainInfos[len(m.ChainInfos)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetSnapshotByIDRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetSnapshotByIDRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetSnapshotByIDRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SnapshotId", wireType)
			}
			m.SnapshotId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SnapshotId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetSnapshotByIDResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetSnapshotByIDResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetSnapshotByIDResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Snapshot", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Snapshot == nil {
				m.Snapshot = &Snapshot{}
			}
			if err := m.Snapshot.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetValidatorAliveUntilRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetValidatorAliveUntilRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetValidatorAliveUntilRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ValAddress", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ValAddress = append(m.ValAddress[:0], dAtA[iNdEx:postIndex]...)
			if m.ValAddress == nil {
				m.ValAddress = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetValidatorAliveUntilResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetValidatorAliveUntilResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetValidatorAliveUntilResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AliveUntil", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_gogo_protobuf_types.StdTimeUnmarshal(&m.AliveUntil, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
