// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	context "context"

	types "github.com/palomachain/pigeon/types/paloma/x/evm/types"
	mock "github.com/stretchr/testify/mock"
)

// MsgServer is an autogenerated mock type for the MsgServer type
type MsgServer struct {
	mock.Mock
}

// SubmitNewJob provides a mock function with given fields: _a0, _a1
func (_m *MsgServer) SubmitNewJob(_a0 context.Context, _a1 *types.MsgSubmitNewJob) (*types.MsgSubmitNewJobResponse, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *types.MsgSubmitNewJobResponse
	if rf, ok := ret.Get(0).(func(context.Context, *types.MsgSubmitNewJob) *types.MsgSubmitNewJobResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.MsgSubmitNewJobResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *types.MsgSubmitNewJob) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UploadNewSmartContractTemp provides a mock function with given fields: _a0, _a1
func (_m *MsgServer) UploadNewSmartContractTemp(_a0 context.Context, _a1 *types.MsgUploadNewSmartContractTemp) (*types.MsgUploadNewSmartContractTempResponse, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *types.MsgUploadNewSmartContractTempResponse
	if rf, ok := ret.Get(0).(func(context.Context, *types.MsgUploadNewSmartContractTemp) *types.MsgUploadNewSmartContractTempResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.MsgUploadNewSmartContractTempResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *types.MsgUploadNewSmartContractTemp) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewMsgServer interface {
	mock.TestingT
	Cleanup(func())
}

// NewMsgServer creates a new instance of MsgServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMsgServer(t mockConstructorTestingTNewMsgServer) *MsgServer {
	mock := &MsgServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
