// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: paloma/query.proto

package paloma

import (
	context "context"
	fmt "fmt"
	types "github.com/cosmos/cosmos-sdk/codec/types"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/cosmos-sdk/types/query"
	_ "github.com/gogo/protobuf/gogoproto"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type ValidatorState int32

const (
	ValidatorState_NONE   ValidatorState = 0
	ValidatorState_ACTIVE ValidatorState = 1
	ValidatorState_JAILED ValidatorState = 2
)

var ValidatorState_name = map[int32]string{
	0: "NONE",
	1: "ACTIVE",
	2: "JAILED",
}

var ValidatorState_value = map[string]int32{
	"NONE":   0,
	"ACTIVE": 1,
	"JAILED": 2,
}

func (x ValidatorState) String() string {
	return proto.EnumName(ValidatorState_name, int32(x))
}

func (ValidatorState) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_0f2cfad067a4dbf8, []int{0}
}

type QueryQueuedMessagesForSigningRequest struct {
	ValAddress    string `protobuf:"bytes,1,opt,name=valAddress,proto3" json:"valAddress,omitempty"`
	QueueTypeName string `protobuf:"bytes,2,opt,name=queueTypeName,proto3" json:"queueTypeName,omitempty"`
}

func (m *QueryQueuedMessagesForSigningRequest) Reset()         { *m = QueryQueuedMessagesForSigningRequest{} }
func (m *QueryQueuedMessagesForSigningRequest) String() string { return proto.CompactTextString(m) }
func (*QueryQueuedMessagesForSigningRequest) ProtoMessage()    {}
func (*QueryQueuedMessagesForSigningRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0f2cfad067a4dbf8, []int{0}
}
func (m *QueryQueuedMessagesForSigningRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryQueuedMessagesForSigningRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryQueuedMessagesForSigningRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryQueuedMessagesForSigningRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryQueuedMessagesForSigningRequest.Merge(m, src)
}
func (m *QueryQueuedMessagesForSigningRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryQueuedMessagesForSigningRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryQueuedMessagesForSigningRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryQueuedMessagesForSigningRequest proto.InternalMessageInfo

func (m *QueryQueuedMessagesForSigningRequest) GetValAddress() string {
	if m != nil {
		return m.ValAddress
	}
	return ""
}

func (m *QueryQueuedMessagesForSigningRequest) GetQueueTypeName() string {
	if m != nil {
		return m.QueueTypeName
	}
	return ""
}

type QueryQueuedMessagesForSigningResponse struct {
	MessageToSign []*MessageToSign `protobuf:"bytes,1,rep,name=messageToSign,proto3" json:"messageToSign,omitempty"`
}

func (m *QueryQueuedMessagesForSigningResponse) Reset()         { *m = QueryQueuedMessagesForSigningResponse{} }
func (m *QueryQueuedMessagesForSigningResponse) String() string { return proto.CompactTextString(m) }
func (*QueryQueuedMessagesForSigningResponse) ProtoMessage()    {}
func (*QueryQueuedMessagesForSigningResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0f2cfad067a4dbf8, []int{1}
}
func (m *QueryQueuedMessagesForSigningResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryQueuedMessagesForSigningResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryQueuedMessagesForSigningResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryQueuedMessagesForSigningResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryQueuedMessagesForSigningResponse.Merge(m, src)
}
func (m *QueryQueuedMessagesForSigningResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryQueuedMessagesForSigningResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryQueuedMessagesForSigningResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryQueuedMessagesForSigningResponse proto.InternalMessageInfo

func (m *QueryQueuedMessagesForSigningResponse) GetMessageToSign() []*MessageToSign {
	if m != nil {
		return m.MessageToSign
	}
	return nil
}

type MessageToSign struct {
	Nonce []byte     `protobuf:"bytes,1,opt,name=nonce,proto3" json:"nonce,omitempty"`
	Id    uint64     `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Msg   *types.Any `protobuf:"bytes,3,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (m *MessageToSign) Reset()         { *m = MessageToSign{} }
func (m *MessageToSign) String() string { return proto.CompactTextString(m) }
func (*MessageToSign) ProtoMessage()    {}
func (*MessageToSign) Descriptor() ([]byte, []int) {
	return fileDescriptor_0f2cfad067a4dbf8, []int{2}
}
func (m *MessageToSign) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MessageToSign) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MessageToSign.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MessageToSign) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageToSign.Merge(m, src)
}
func (m *MessageToSign) XXX_Size() int {
	return m.Size()
}
func (m *MessageToSign) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageToSign.DiscardUnknown(m)
}

var xxx_messageInfo_MessageToSign proto.InternalMessageInfo

func (m *MessageToSign) GetNonce() []byte {
	if m != nil {
		return m.Nonce
	}
	return nil
}

func (m *MessageToSign) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *MessageToSign) GetMsg() *types.Any {
	if m != nil {
		return m.Msg
	}
	return nil
}

type QueryValidatorInfoRequest struct {
	ValAddr string `protobuf:"bytes,1,opt,name=valAddr,proto3" json:"valAddr,omitempty"`
}

func (m *QueryValidatorInfoRequest) Reset()         { *m = QueryValidatorInfoRequest{} }
func (m *QueryValidatorInfoRequest) String() string { return proto.CompactTextString(m) }
func (*QueryValidatorInfoRequest) ProtoMessage()    {}
func (*QueryValidatorInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0f2cfad067a4dbf8, []int{3}
}
func (m *QueryValidatorInfoRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryValidatorInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryValidatorInfoRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryValidatorInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryValidatorInfoRequest.Merge(m, src)
}
func (m *QueryValidatorInfoRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryValidatorInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryValidatorInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryValidatorInfoRequest proto.InternalMessageInfo

func (m *QueryValidatorInfoRequest) GetValAddr() string {
	if m != nil {
		return m.ValAddr
	}
	return ""
}

type QueryValidatorInfoResponse struct {
	Validator *Validator `protobuf:"bytes,1,opt,name=validator,proto3" json:"validator,omitempty"`
}

func (m *QueryValidatorInfoResponse) Reset()         { *m = QueryValidatorInfoResponse{} }
func (m *QueryValidatorInfoResponse) String() string { return proto.CompactTextString(m) }
func (*QueryValidatorInfoResponse) ProtoMessage()    {}
func (*QueryValidatorInfoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0f2cfad067a4dbf8, []int{4}
}
func (m *QueryValidatorInfoResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryValidatorInfoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryValidatorInfoResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryValidatorInfoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryValidatorInfoResponse.Merge(m, src)
}
func (m *QueryValidatorInfoResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryValidatorInfoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryValidatorInfoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryValidatorInfoResponse proto.InternalMessageInfo

func (m *QueryValidatorInfoResponse) GetValidator() *Validator {
	if m != nil {
		return m.Validator
	}
	return nil
}

type Validator struct {
	ShareCount github_com_cosmos_cosmos_sdk_types.Int `protobuf:"bytes,1,opt,name=shareCount,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Int" json:"shareCount"`
	// TODO: make this ed25519 pub key instead of bytes
	PubKey             []byte               `protobuf:"bytes,2,opt,name=pubKey,proto3" json:"pubKey,omitempty"`
	State              ValidatorState       `protobuf:"varint,3,opt,name=state,proto3,enum=volumefi.paloma.consensus.ValidatorState" json:"state,omitempty"`
	ExternalChainInfos []*ExternalChainInfo `protobuf:"bytes,4,rep,name=externalChainInfos,proto3" json:"externalChainInfos,omitempty"`
	Address            string               `protobuf:"bytes,5,opt,name=address,proto3" json:"address,omitempty"`
}

func (m *Validator) Reset()         { *m = Validator{} }
func (m *Validator) String() string { return proto.CompactTextString(m) }
func (*Validator) ProtoMessage()    {}
func (*Validator) Descriptor() ([]byte, []int) {
	return fileDescriptor_0f2cfad067a4dbf8, []int{5}
}
func (m *Validator) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Validator) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Validator.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Validator) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Validator.Merge(m, src)
}
func (m *Validator) XXX_Size() int {
	return m.Size()
}
func (m *Validator) XXX_DiscardUnknown() {
	xxx_messageInfo_Validator.DiscardUnknown(m)
}

var xxx_messageInfo_Validator proto.InternalMessageInfo

func (m *Validator) GetPubKey() []byte {
	if m != nil {
		return m.PubKey
	}
	return nil
}

func (m *Validator) GetState() ValidatorState {
	if m != nil {
		return m.State
	}
	return ValidatorState_NONE
}

func (m *Validator) GetExternalChainInfos() []*ExternalChainInfo {
	if m != nil {
		return m.ExternalChainInfos
	}
	return nil
}

func (m *Validator) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type ExternalChainInfo struct {
	ID      uint64 `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	ChainID string `protobuf:"bytes,2,opt,name=chainID,proto3" json:"chainID,omitempty"`
	Address string `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
}

func (m *ExternalChainInfo) Reset()         { *m = ExternalChainInfo{} }
func (m *ExternalChainInfo) String() string { return proto.CompactTextString(m) }
func (*ExternalChainInfo) ProtoMessage()    {}
func (*ExternalChainInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_0f2cfad067a4dbf8, []int{6}
}
func (m *ExternalChainInfo) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ExternalChainInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ExternalChainInfo.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ExternalChainInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExternalChainInfo.Merge(m, src)
}
func (m *ExternalChainInfo) XXX_Size() int {
	return m.Size()
}
func (m *ExternalChainInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ExternalChainInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ExternalChainInfo proto.InternalMessageInfo

func (m *ExternalChainInfo) GetID() uint64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *ExternalChainInfo) GetChainID() string {
	if m != nil {
		return m.ChainID
	}
	return ""
}

func (m *ExternalChainInfo) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func init() {
	proto.RegisterEnum("volumefi.paloma.consensus.ValidatorState", ValidatorState_name, ValidatorState_value)
	proto.RegisterType((*QueryQueuedMessagesForSigningRequest)(nil), "volumefi.paloma.consensus.QueryQueuedMessagesForSigningRequest")
	proto.RegisterType((*QueryQueuedMessagesForSigningResponse)(nil), "volumefi.paloma.consensus.QueryQueuedMessagesForSigningResponse")
	proto.RegisterType((*MessageToSign)(nil), "volumefi.paloma.consensus.MessageToSign")
	proto.RegisterType((*QueryValidatorInfoRequest)(nil), "volumefi.paloma.consensus.QueryValidatorInfoRequest")
	proto.RegisterType((*QueryValidatorInfoResponse)(nil), "volumefi.paloma.consensus.QueryValidatorInfoResponse")
	proto.RegisterType((*Validator)(nil), "volumefi.paloma.consensus.Validator")
	proto.RegisterType((*ExternalChainInfo)(nil), "volumefi.paloma.consensus.ExternalChainInfo")
}

func init() { proto.RegisterFile("paloma/query.proto", fileDescriptor_0f2cfad067a4dbf8) }

var fileDescriptor_0f2cfad067a4dbf8 = []byte{
	// 744 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x54, 0xdd, 0x6a, 0x13, 0x41,
	0x14, 0xce, 0xe6, 0xa7, 0xda, 0x93, 0xa6, 0xd4, 0xa1, 0x48, 0x1a, 0x24, 0x2d, 0x4b, 0x2d, 0xb1,
	0xe8, 0xae, 0x5d, 0xad, 0xf4, 0xca, 0x9a, 0x36, 0x11, 0xa2, 0x36, 0xd2, 0x6d, 0xa9, 0x20, 0x4a,
	0x9c, 0x64, 0x27, 0xdb, 0xc5, 0x64, 0x66, 0xbb, 0xb3, 0x1b, 0x0d, 0xe2, 0x8d, 0x4f, 0x20, 0xf8,
	0x1a, 0x5e, 0xfb, 0x08, 0xd2, 0xcb, 0x82, 0x37, 0x22, 0x58, 0xa4, 0x15, 0x7c, 0x0d, 0xd9, 0xd9,
	0x49, 0x4c, 0xec, 0xaf, 0x5e, 0xed, 0x9e, 0x3d, 0xe7, 0xfb, 0xe6, 0x9c, 0x6f, 0xcf, 0x37, 0x80,
	0x5c, 0xdc, 0x62, 0x6d, 0xac, 0xef, 0x04, 0xc4, 0xeb, 0x6a, 0xae, 0xc7, 0x7c, 0x86, 0xa6, 0x3a,
	0xac, 0x15, 0xb4, 0x49, 0xd3, 0xd1, 0xa2, 0xa4, 0xd6, 0x60, 0x94, 0x13, 0xca, 0x03, 0x9e, 0x9b,
	0xb4, 0x99, 0xcd, 0x44, 0x95, 0x1e, 0xbe, 0x45, 0x80, 0xdc, 0x15, 0x9b, 0x31, 0xbb, 0x45, 0x74,
	0xec, 0x3a, 0x3a, 0xa6, 0x94, 0xf9, 0xd8, 0x77, 0x18, 0xe5, 0x32, 0x3b, 0xdf, 0x60, 0xbc, 0xcd,
	0xb8, 0x5e, 0xc7, 0x9c, 0x44, 0xe7, 0xe8, 0x9d, 0x85, 0x3a, 0xf1, 0xf1, 0x82, 0xee, 0x62, 0xdb,
	0xa1, 0xa2, 0x58, 0xd6, 0x4e, 0x49, 0x26, 0x11, 0xd5, 0x83, 0xa6, 0x8e, 0xa9, 0xec, 0x4a, 0x6d,
	0xc1, 0xec, 0x7a, 0x08, 0x5e, 0x0f, 0x48, 0x40, 0xac, 0x35, 0xc2, 0x39, 0xb6, 0x09, 0xbf, 0xcf,
	0xbc, 0x0d, 0xc7, 0xa6, 0x0e, 0xb5, 0x4d, 0xb2, 0x13, 0x10, 0xee, 0xa3, 0x3c, 0x40, 0x07, 0xb7,
	0x8a, 0x96, 0xe5, 0x11, 0xce, 0xb3, 0xca, 0x8c, 0x52, 0x18, 0x35, 0x07, 0xbe, 0xa0, 0x59, 0xc8,
	0xec, 0x84, 0x14, 0x9b, 0x5d, 0x97, 0x54, 0x71, 0x9b, 0x64, 0xe3, 0xa2, 0x64, 0xf8, 0xa3, 0xfa,
	0x0a, 0xae, 0x9e, 0x71, 0x1a, 0x77, 0x43, 0x55, 0x50, 0x15, 0x32, 0xed, 0x28, 0xbb, 0xc9, 0xc2,
	0x5c, 0x56, 0x99, 0x49, 0x14, 0xd2, 0x46, 0x41, 0x3b, 0x51, 0x44, 0x6d, 0x6d, 0xb0, 0xde, 0x1c,
	0x86, 0xab, 0xcf, 0x21, 0x33, 0x94, 0x47, 0x93, 0x90, 0xa2, 0x8c, 0x36, 0x88, 0x18, 0x65, 0xcc,
	0x8c, 0x02, 0x34, 0x0e, 0x71, 0xc7, 0x12, 0xad, 0x27, 0xcd, 0xb8, 0x63, 0xa1, 0x39, 0x48, 0xb4,
	0xb9, 0x9d, 0x4d, 0xcc, 0x28, 0x85, 0xb4, 0x31, 0xa9, 0x45, 0x32, 0x6a, 0x3d, 0x19, 0xb5, 0x22,
	0xed, 0x9a, 0x61, 0x81, 0xba, 0x08, 0x53, 0x62, 0xae, 0x2d, 0xdc, 0x72, 0x2c, 0xec, 0x33, 0xaf,
	0x42, 0x9b, 0xac, 0x27, 0x5d, 0x16, 0x2e, 0x48, 0xa1, 0xa4, 0x6e, 0xbd, 0x50, 0x7d, 0x01, 0xb9,
	0xe3, 0x60, 0x52, 0x83, 0x15, 0x18, 0xed, 0xf4, 0x12, 0x02, 0x99, 0x36, 0x66, 0x4f, 0x99, 0xbf,
	0x4f, 0x62, 0xfe, 0x81, 0xa9, 0x1f, 0xe3, 0x30, 0xda, 0x4f, 0xa0, 0x2a, 0x00, 0xdf, 0xc6, 0x1e,
	0x59, 0x65, 0x01, 0xf5, 0xa3, 0xc9, 0x57, 0xb4, 0xdd, 0xfd, 0xe9, 0xd8, 0xb7, 0xfd, 0xe9, 0x39,
	0xdb, 0xf1, 0xb7, 0x83, 0xba, 0xd6, 0x60, 0x6d, 0x5d, 0xae, 0x56, 0xf4, 0xb8, 0xc1, 0xad, 0x97,
	0xba, 0xdf, 0x75, 0x09, 0xd7, 0x2a, 0xd4, 0x37, 0x07, 0x18, 0xd0, 0x65, 0x18, 0x71, 0x83, 0xfa,
	0x43, 0xd2, 0x15, 0x92, 0x8d, 0x99, 0x32, 0x42, 0xcb, 0x90, 0xe2, 0x3e, 0xf6, 0x89, 0x10, 0x6e,
	0xdc, 0xb8, 0x76, 0x9e, 0xae, 0x37, 0x42, 0x80, 0x19, 0xe1, 0xd0, 0x33, 0x40, 0xe4, 0xb5, 0x4f,
	0x3c, 0x8a, 0x5b, 0xab, 0xdb, 0xd8, 0xa1, 0xa1, 0x2e, 0x3c, 0x9b, 0x14, 0x3b, 0x70, 0xfd, 0x14,
	0xb6, 0xf2, 0xdf, 0x20, 0xf3, 0x18, 0x9e, 0xf0, 0x87, 0x60, 0xb9, 0xc8, 0xa9, 0xe8, 0x87, 0xc8,
	0x50, 0x7d, 0x02, 0x97, 0x8e, 0x50, 0x84, 0x4b, 0x51, 0x29, 0x09, 0xb5, 0x92, 0x66, 0xbc, 0x52,
	0x0a, 0xe1, 0x0d, 0x91, 0x2c, 0xc9, 0x25, 0xef, 0x85, 0x83, 0xc4, 0x89, 0x21, 0xe2, 0x79, 0x03,
	0xc6, 0x87, 0x27, 0x45, 0x17, 0x21, 0x59, 0x7d, 0x5c, 0x2d, 0x4f, 0xc4, 0x10, 0xc0, 0x48, 0x71,
	0x75, 0xb3, 0xb2, 0x55, 0x9e, 0x50, 0xc2, 0xf7, 0x07, 0xc5, 0xca, 0xa3, 0x72, 0x69, 0x22, 0x6e,
	0xfc, 0x52, 0x20, 0x25, 0xd6, 0x03, 0x7d, 0x57, 0x20, 0x7b, 0x92, 0x65, 0xd0, 0xf2, 0x29, 0x7a,
	0x9c, 0xc7, 0xda, 0xb9, 0x7b, 0xff, 0x4f, 0x10, 0x6d, 0xaa, 0x7a, 0xf7, 0xdd, 0x97, 0x9f, 0x1f,
	0xe2, 0x4b, 0xe8, 0x8e, 0xde, 0x63, 0xd2, 0xe5, 0x05, 0xd8, 0x67, 0xd2, 0xc5, 0x45, 0x60, 0xd5,
	0xa4, 0x2d, 0x79, 0xad, 0xc9, 0xbc, 0x1a, 0x8f, 0x78, 0x8c, 0xcf, 0x0a, 0xa4, 0x7b, 0x46, 0xe0,
	0xc4, 0x47, 0x9f, 0x14, 0xc8, 0x0c, 0x79, 0x02, 0xdd, 0x3e, 0xab, 0xc7, 0xe3, 0x9c, 0x97, 0x5b,
	0xfc, 0x47, 0x94, 0x1c, 0x67, 0x49, 0x8c, 0x63, 0xa0, 0x9b, 0x47, 0xc6, 0xe9, 0x88, 0xfe, 0xf4,
	0xbe, 0xbf, 0x6a, 0x0e, 0x6d, 0x32, 0xfd, 0x8d, 0xf4, 0xf3, 0xdb, 0x95, 0xd2, 0xee, 0x41, 0x5e,
	0xd9, 0x3b, 0xc8, 0x2b, 0x3f, 0x0e, 0xf2, 0xca, 0xfb, 0xc3, 0x7c, 0x6c, 0xef, 0x30, 0x1f, 0xfb,
	0x7a, 0x98, 0x8f, 0x3d, 0x9d, 0x1f, 0xb0, 0x57, 0x9f, 0xb5, 0xc1, 0xa8, 0x15, 0x34, 0x7c, 0xe6,
	0x45, 0xfe, 0x92, 0xa7, 0xd4, 0x47, 0xc4, 0x05, 0x73, 0xeb, 0x77, 0x00, 0x00, 0x00, 0xff, 0xff,
	0x7a, 0xc7, 0xf3, 0x10, 0x46, 0x06, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Queries a list of QueuedMessagesForSigning items.
	QueuedMessagesForSigning(ctx context.Context, in *QueryQueuedMessagesForSigningRequest, opts ...grpc.CallOption) (*QueryQueuedMessagesForSigningResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) QueuedMessagesForSigning(ctx context.Context, in *QueryQueuedMessagesForSigningRequest, opts ...grpc.CallOption) (*QueryQueuedMessagesForSigningResponse, error) {
	out := new(QueryQueuedMessagesForSigningResponse)
	err := c.cc.Invoke(ctx, "/volumefi.paloma.consensus.Query/QueuedMessagesForSigning", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Queries a list of QueuedMessagesForSigning items.
	QueuedMessagesForSigning(context.Context, *QueryQueuedMessagesForSigningRequest) (*QueryQueuedMessagesForSigningResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) QueuedMessagesForSigning(ctx context.Context, req *QueryQueuedMessagesForSigningRequest) (*QueryQueuedMessagesForSigningResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueuedMessagesForSigning not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_QueuedMessagesForSigning_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryQueuedMessagesForSigningRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).QueuedMessagesForSigning(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/volumefi.paloma.consensus.Query/QueuedMessagesForSigning",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).QueuedMessagesForSigning(ctx, req.(*QueryQueuedMessagesForSigningRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "volumefi.paloma.consensus.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "QueuedMessagesForSigning",
			Handler:    _Query_QueuedMessagesForSigning_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "paloma/query.proto",
}

// QueryValsetClient is the client API for QueryValset service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryValsetClient interface {
	ValidatorInfo(ctx context.Context, in *QueryValidatorInfoRequest, opts ...grpc.CallOption) (*QueryValidatorInfoResponse, error)
}

type queryValsetClient struct {
	cc grpc1.ClientConn
}

func NewQueryValsetClient(cc grpc1.ClientConn) QueryValsetClient {
	return &queryValsetClient{cc}
}

func (c *queryValsetClient) ValidatorInfo(ctx context.Context, in *QueryValidatorInfoRequest, opts ...grpc.CallOption) (*QueryValidatorInfoResponse, error) {
	out := new(QueryValidatorInfoResponse)
	err := c.cc.Invoke(ctx, "/volumefi.paloma.consensus.QueryValset/ValidatorInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryValsetServer is the server API for QueryValset service.
type QueryValsetServer interface {
	ValidatorInfo(context.Context, *QueryValidatorInfoRequest) (*QueryValidatorInfoResponse, error)
}

// UnimplementedQueryValsetServer can be embedded to have forward compatible implementations.
type UnimplementedQueryValsetServer struct {
}

func (*UnimplementedQueryValsetServer) ValidatorInfo(ctx context.Context, req *QueryValidatorInfoRequest) (*QueryValidatorInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ValidatorInfo not implemented")
}

func RegisterQueryValsetServer(s grpc1.Server, srv QueryValsetServer) {
	s.RegisterService(&_QueryValset_serviceDesc, srv)
}

func _QueryValset_ValidatorInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryValidatorInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryValsetServer).ValidatorInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/volumefi.paloma.consensus.QueryValset/ValidatorInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryValsetServer).ValidatorInfo(ctx, req.(*QueryValidatorInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _QueryValset_serviceDesc = grpc.ServiceDesc{
	ServiceName: "volumefi.paloma.consensus.QueryValset",
	HandlerType: (*QueryValsetServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ValidatorInfo",
			Handler:    _QueryValset_ValidatorInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "paloma/query.proto",
}

func (m *QueryQueuedMessagesForSigningRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryQueuedMessagesForSigningRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryQueuedMessagesForSigningRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.QueueTypeName) > 0 {
		i -= len(m.QueueTypeName)
		copy(dAtA[i:], m.QueueTypeName)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.QueueTypeName)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.ValAddress) > 0 {
		i -= len(m.ValAddress)
		copy(dAtA[i:], m.ValAddress)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.ValAddress)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryQueuedMessagesForSigningResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryQueuedMessagesForSigningResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryQueuedMessagesForSigningResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.MessageToSign) > 0 {
		for iNdEx := len(m.MessageToSign) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.MessageToSign[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *MessageToSign) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MessageToSign) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MessageToSign) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Msg != nil {
		{
			size, err := m.Msg.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1a
	}
	if m.Id != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Nonce) > 0 {
		i -= len(m.Nonce)
		copy(dAtA[i:], m.Nonce)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Nonce)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryValidatorInfoRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryValidatorInfoRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryValidatorInfoRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.ValAddr) > 0 {
		i -= len(m.ValAddr)
		copy(dAtA[i:], m.ValAddr)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.ValAddr)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryValidatorInfoResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryValidatorInfoResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryValidatorInfoResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Validator != nil {
		{
			size, err := m.Validator.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *Validator) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Validator) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Validator) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.ExternalChainInfos) > 0 {
		for iNdEx := len(m.ExternalChainInfos) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.ExternalChainInfos[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x22
		}
	}
	if m.State != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.State))
		i--
		dAtA[i] = 0x18
	}
	if len(m.PubKey) > 0 {
		i -= len(m.PubKey)
		copy(dAtA[i:], m.PubKey)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.PubKey)))
		i--
		dAtA[i] = 0x12
	}
	{
		size := m.ShareCount.Size()
		i -= size
		if _, err := m.ShareCount.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *ExternalChainInfo) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ExternalChainInfo) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ExternalChainInfo) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.ChainID) > 0 {
		i -= len(m.ChainID)
		copy(dAtA[i:], m.ChainID)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.ChainID)))
		i--
		dAtA[i] = 0x12
	}
	if m.ID != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.ID))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryQueuedMessagesForSigningRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ValAddress)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	l = len(m.QueueTypeName)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryQueuedMessagesForSigningResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.MessageToSign) > 0 {
		for _, e := range m.MessageToSign {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	return n
}

func (m *MessageToSign) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Nonce)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	if m.Id != 0 {
		n += 1 + sovQuery(uint64(m.Id))
	}
	if m.Msg != nil {
		l = m.Msg.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryValidatorInfoRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ValAddr)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryValidatorInfoResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Validator != nil {
		l = m.Validator.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *Validator) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.ShareCount.Size()
	n += 1 + l + sovQuery(uint64(l))
	l = len(m.PubKey)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	if m.State != 0 {
		n += 1 + sovQuery(uint64(m.State))
	}
	if len(m.ExternalChainInfos) > 0 {
		for _, e := range m.ExternalChainInfos {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *ExternalChainInfo) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.ID != 0 {
		n += 1 + sovQuery(uint64(m.ID))
	}
	l = len(m.ChainID)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryQueuedMessagesForSigningRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryQueuedMessagesForSigningRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryQueuedMessagesForSigningRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ValAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ValAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field QueueTypeName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.QueueTypeName = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryQueuedMessagesForSigningResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryQueuedMessagesForSigningResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryQueuedMessagesForSigningResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MessageToSign", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MessageToSign = append(m.MessageToSign, &MessageToSign{})
			if err := m.MessageToSign[len(m.MessageToSign)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MessageToSign) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MessageToSign: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MessageToSign: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Nonce", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Nonce = append(m.Nonce[:0], dAtA[iNdEx:postIndex]...)
			if m.Nonce == nil {
				m.Nonce = []byte{}
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Msg", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Msg == nil {
				m.Msg = &types.Any{}
			}
			if err := m.Msg.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryValidatorInfoRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryValidatorInfoRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryValidatorInfoRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ValAddr", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ValAddr = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryValidatorInfoResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryValidatorInfoResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryValidatorInfoResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Validator", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Validator == nil {
				m.Validator = &Validator{}
			}
			if err := m.Validator.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Validator) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Validator: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Validator: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ShareCount", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.ShareCount.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PubKey", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PubKey = append(m.PubKey[:0], dAtA[iNdEx:postIndex]...)
			if m.PubKey == nil {
				m.PubKey = []byte{}
			}
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field State", wireType)
			}
			m.State = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.State |= ValidatorState(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ExternalChainInfos", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ExternalChainInfos = append(m.ExternalChainInfos, &ExternalChainInfo{})
			if err := m.ExternalChainInfos[len(m.ExternalChainInfos)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ExternalChainInfo) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ExternalChainInfo: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ExternalChainInfo: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ID", wireType)
			}
			m.ID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ID |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ChainID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ChainID = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
