// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: cronchain/query.proto

package cronchain

import (
	context "context"
	fmt "fmt"
	types "github.com/cosmos/cosmos-sdk/codec/types"
	_ "github.com/cosmos/cosmos-sdk/types/query"
	_ "github.com/gogo/protobuf/gogoproto"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type QueryQueuedMessagesForSigningRequest struct {
	ValAddress    string `protobuf:"bytes,1,opt,name=valAddress,proto3" json:"valAddress,omitempty"`
	QueueTypeName string `protobuf:"bytes,2,opt,name=queueTypeName,proto3" json:"queueTypeName,omitempty"`
}

func (m *QueryQueuedMessagesForSigningRequest) Reset()         { *m = QueryQueuedMessagesForSigningRequest{} }
func (m *QueryQueuedMessagesForSigningRequest) String() string { return proto.CompactTextString(m) }
func (*QueryQueuedMessagesForSigningRequest) ProtoMessage()    {}
func (*QueryQueuedMessagesForSigningRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e104e1a2c4ac5aa2, []int{0}
}
func (m *QueryQueuedMessagesForSigningRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryQueuedMessagesForSigningRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryQueuedMessagesForSigningRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryQueuedMessagesForSigningRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryQueuedMessagesForSigningRequest.Merge(m, src)
}
func (m *QueryQueuedMessagesForSigningRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryQueuedMessagesForSigningRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryQueuedMessagesForSigningRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryQueuedMessagesForSigningRequest proto.InternalMessageInfo

func (m *QueryQueuedMessagesForSigningRequest) GetValAddress() string {
	if m != nil {
		return m.ValAddress
	}
	return ""
}

func (m *QueryQueuedMessagesForSigningRequest) GetQueueTypeName() string {
	if m != nil {
		return m.QueueTypeName
	}
	return ""
}

type QueryQueuedMessagesForSigningResponse struct {
	MessageToSign []*MessageToSign `protobuf:"bytes,1,rep,name=messageToSign,proto3" json:"messageToSign,omitempty"`
}

func (m *QueryQueuedMessagesForSigningResponse) Reset()         { *m = QueryQueuedMessagesForSigningResponse{} }
func (m *QueryQueuedMessagesForSigningResponse) String() string { return proto.CompactTextString(m) }
func (*QueryQueuedMessagesForSigningResponse) ProtoMessage()    {}
func (*QueryQueuedMessagesForSigningResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e104e1a2c4ac5aa2, []int{1}
}
func (m *QueryQueuedMessagesForSigningResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryQueuedMessagesForSigningResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryQueuedMessagesForSigningResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryQueuedMessagesForSigningResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryQueuedMessagesForSigningResponse.Merge(m, src)
}
func (m *QueryQueuedMessagesForSigningResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryQueuedMessagesForSigningResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryQueuedMessagesForSigningResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryQueuedMessagesForSigningResponse proto.InternalMessageInfo

func (m *QueryQueuedMessagesForSigningResponse) GetMessageToSign() []*MessageToSign {
	if m != nil {
		return m.MessageToSign
	}
	return nil
}

type MessageToSign struct {
	Nonce []byte     `protobuf:"bytes,1,opt,name=nonce,proto3" json:"nonce,omitempty"`
	Id    uint64     `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Msg   *types.Any `protobuf:"bytes,3,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (m *MessageToSign) Reset()         { *m = MessageToSign{} }
func (m *MessageToSign) String() string { return proto.CompactTextString(m) }
func (*MessageToSign) ProtoMessage()    {}
func (*MessageToSign) Descriptor() ([]byte, []int) {
	return fileDescriptor_e104e1a2c4ac5aa2, []int{2}
}
func (m *MessageToSign) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MessageToSign) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MessageToSign.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MessageToSign) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageToSign.Merge(m, src)
}
func (m *MessageToSign) XXX_Size() int {
	return m.Size()
}
func (m *MessageToSign) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageToSign.DiscardUnknown(m)
}

var xxx_messageInfo_MessageToSign proto.InternalMessageInfo

func (m *MessageToSign) GetNonce() []byte {
	if m != nil {
		return m.Nonce
	}
	return nil
}

func (m *MessageToSign) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *MessageToSign) GetMsg() *types.Any {
	if m != nil {
		return m.Msg
	}
	return nil
}

func init() {
	proto.RegisterType((*QueryQueuedMessagesForSigningRequest)(nil), "volumefi.cronchain.concensus.QueryQueuedMessagesForSigningRequest")
	proto.RegisterType((*QueryQueuedMessagesForSigningResponse)(nil), "volumefi.cronchain.concensus.QueryQueuedMessagesForSigningResponse")
	proto.RegisterType((*MessageToSign)(nil), "volumefi.cronchain.concensus.MessageToSign")
}

func init() { proto.RegisterFile("cronchain/query.proto", fileDescriptor_e104e1a2c4ac5aa2) }

var fileDescriptor_e104e1a2c4ac5aa2 = []byte{
	// 447 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x92, 0x41, 0x6b, 0x13, 0x41,
	0x14, 0xc7, 0x3b, 0x89, 0x15, 0x9c, 0x1a, 0x0f, 0x43, 0x84, 0x35, 0x94, 0x25, 0x84, 0x2a, 0x41,
	0x71, 0x86, 0xc6, 0x93, 0x78, 0x4a, 0x05, 0x3d, 0x55, 0xc8, 0xda, 0x93, 0x20, 0x61, 0x76, 0x77,
	0x32, 0x1d, 0xc8, 0xce, 0xdb, 0xec, 0xdb, 0x09, 0xc4, 0xa3, 0x9f, 0x40, 0xf0, 0x4b, 0x79, 0x2c,
	0x78, 0xf1, 0x28, 0x89, 0x78, 0xf6, 0x23, 0xc8, 0xce, 0x6e, 0xdb, 0xe4, 0x60, 0x15, 0xbc, 0xed,
	0xcc, 0xff, 0xff, 0x7e, 0x6f, 0xde, 0xff, 0x2d, 0xbd, 0x9f, 0x14, 0x60, 0x93, 0x73, 0x69, 0xac,
	0x58, 0x38, 0x55, 0xac, 0x78, 0x5e, 0x40, 0x09, 0xec, 0x70, 0x09, 0x73, 0x97, 0xa9, 0x99, 0xe1,
	0x57, 0x3a, 0x4f, 0xc0, 0x26, 0xca, 0xa2, 0xc3, 0x5e, 0x57, 0x83, 0x06, 0x6f, 0x14, 0xd5, 0x57,
	0x5d, 0xd3, 0x3b, 0xd4, 0x00, 0x7a, 0xae, 0x84, 0xcc, 0x8d, 0x90, 0xd6, 0x42, 0x29, 0x4b, 0x03,
	0x16, 0x1b, 0xf5, 0x71, 0x02, 0x98, 0x01, 0x8a, 0x58, 0xa2, 0xaa, 0x5b, 0x89, 0xe5, 0x71, 0xac,
	0x4a, 0x79, 0x2c, 0x72, 0xa9, 0x8d, 0xf5, 0xe6, 0xc6, 0xfb, 0xa0, 0x21, 0xf9, 0x53, 0xec, 0x66,
	0x42, 0xda, 0xe6, 0x61, 0x83, 0x39, 0x3d, 0x9a, 0x54, 0xc5, 0x13, 0xa7, 0x9c, 0x4a, 0x4f, 0x15,
	0xa2, 0xd4, 0x0a, 0x5f, 0x41, 0xf1, 0xd6, 0x68, 0x6b, 0xac, 0x8e, 0xd4, 0xc2, 0x29, 0x2c, 0x59,
	0x48, 0xe9, 0x52, 0xce, 0xc7, 0x69, 0x5a, 0x28, 0xc4, 0x80, 0xf4, 0xc9, 0xf0, 0x4e, 0xb4, 0x75,
	0xc3, 0x8e, 0x68, 0x67, 0x51, 0x21, 0xce, 0x56, 0xb9, 0x7a, 0x23, 0x33, 0x15, 0xb4, 0xbc, 0x65,
	0xf7, 0x72, 0xf0, 0x81, 0x3e, 0xfc, 0x4b, 0x37, 0xcc, 0xc1, 0xa2, 0x62, 0x13, 0xda, 0xc9, 0x6a,
	0xf5, 0x0c, 0x2a, 0x2d, 0x20, 0xfd, 0xf6, 0xf0, 0x60, 0xf4, 0x84, 0xdf, 0x94, 0x23, 0x3f, 0xdd,
	0x2e, 0x89, 0x76, 0x09, 0x83, 0xf7, 0xb4, 0xb3, 0xa3, 0xb3, 0x2e, 0xdd, 0xb7, 0x55, 0xa9, 0x9f,
	0xe6, 0x6e, 0x54, 0x1f, 0xd8, 0x3d, 0xda, 0x32, 0xa9, 0x7f, 0xfd, 0xad, 0xa8, 0x65, 0x52, 0xf6,
	0x88, 0xb6, 0x33, 0xd4, 0x41, 0xbb, 0x4f, 0x86, 0x07, 0xa3, 0x2e, 0xaf, 0x93, 0xe4, 0x97, 0x49,
	0xf2, 0xb1, 0x5d, 0x45, 0x95, 0x61, 0xf4, 0x8b, 0xd0, 0x7d, 0x3f, 0x1b, 0xfb, 0x49, 0x68, 0xf0,
	0xa7, 0x01, 0xd9, 0xc9, 0xcd, 0x13, 0xfc, 0xcb, 0x2e, 0x7a, 0x2f, 0xff, 0x8b, 0x51, 0x27, 0x3c,
	0x18, 0x7f, 0xfc, 0xfa, 0xe3, 0x73, 0xeb, 0x05, 0x7b, 0x2e, 0x2e, 0x61, 0xe2, 0xfa, 0xd7, 0xbd,
	0x82, 0x09, 0xbf, 0xbf, 0x74, 0xda, 0x44, 0x89, 0xd3, 0x19, 0x14, 0x53, 0xac, 0x51, 0x27, 0xaf,
	0xbf, 0xac, 0x43, 0x72, 0xb1, 0x0e, 0xc9, 0xf7, 0x75, 0x48, 0x3e, 0x6d, 0xc2, 0xbd, 0x8b, 0x4d,
	0xb8, 0xf7, 0x6d, 0x13, 0xee, 0xbd, 0x7b, 0xaa, 0x4d, 0x79, 0xee, 0x62, 0x9e, 0x40, 0xb6, 0x85,
	0x07, 0x9b, 0xba, 0xa4, 0x84, 0x42, 0x94, 0xab, 0x5c, 0xe1, 0x75, 0xbb, 0xf8, 0xb6, 0x8f, 0xf3,
	0xd9, 0xef, 0x00, 0x00, 0x00, 0xff, 0xff, 0x67, 0xe3, 0xd3, 0x49, 0x3d, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Queries a list of QueuedMessagesForSigning items.
	QueuedMessagesForSigning(ctx context.Context, in *QueryQueuedMessagesForSigningRequest, opts ...grpc.CallOption) (*QueryQueuedMessagesForSigningResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) QueuedMessagesForSigning(ctx context.Context, in *QueryQueuedMessagesForSigningRequest, opts ...grpc.CallOption) (*QueryQueuedMessagesForSigningResponse, error) {
	out := new(QueryQueuedMessagesForSigningResponse)
	err := c.cc.Invoke(ctx, "/volumefi.cronchain.concensus.Query/QueuedMessagesForSigning", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Queries a list of QueuedMessagesForSigning items.
	QueuedMessagesForSigning(context.Context, *QueryQueuedMessagesForSigningRequest) (*QueryQueuedMessagesForSigningResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) QueuedMessagesForSigning(ctx context.Context, req *QueryQueuedMessagesForSigningRequest) (*QueryQueuedMessagesForSigningResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueuedMessagesForSigning not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_QueuedMessagesForSigning_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryQueuedMessagesForSigningRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).QueuedMessagesForSigning(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/volumefi.cronchain.concensus.Query/QueuedMessagesForSigning",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).QueuedMessagesForSigning(ctx, req.(*QueryQueuedMessagesForSigningRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "volumefi.cronchain.concensus.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "QueuedMessagesForSigning",
			Handler:    _Query_QueuedMessagesForSigning_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cronchain/query.proto",
}

func (m *QueryQueuedMessagesForSigningRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryQueuedMessagesForSigningRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryQueuedMessagesForSigningRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.QueueTypeName) > 0 {
		i -= len(m.QueueTypeName)
		copy(dAtA[i:], m.QueueTypeName)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.QueueTypeName)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.ValAddress) > 0 {
		i -= len(m.ValAddress)
		copy(dAtA[i:], m.ValAddress)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.ValAddress)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryQueuedMessagesForSigningResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryQueuedMessagesForSigningResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryQueuedMessagesForSigningResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.MessageToSign) > 0 {
		for iNdEx := len(m.MessageToSign) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.MessageToSign[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *MessageToSign) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MessageToSign) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MessageToSign) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Msg != nil {
		{
			size, err := m.Msg.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1a
	}
	if m.Id != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Nonce) > 0 {
		i -= len(m.Nonce)
		copy(dAtA[i:], m.Nonce)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Nonce)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryQueuedMessagesForSigningRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ValAddress)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	l = len(m.QueueTypeName)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryQueuedMessagesForSigningResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.MessageToSign) > 0 {
		for _, e := range m.MessageToSign {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	return n
}

func (m *MessageToSign) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Nonce)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	if m.Id != 0 {
		n += 1 + sovQuery(uint64(m.Id))
	}
	if m.Msg != nil {
		l = m.Msg.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryQueuedMessagesForSigningRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryQueuedMessagesForSigningRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryQueuedMessagesForSigningRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ValAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ValAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field QueueTypeName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.QueueTypeName = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryQueuedMessagesForSigningResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryQueuedMessagesForSigningResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryQueuedMessagesForSigningResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MessageToSign", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MessageToSign = append(m.MessageToSign, &MessageToSign{})
			if err := m.MessageToSign[len(m.MessageToSign)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MessageToSign) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MessageToSign: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MessageToSign: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Nonce", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Nonce = append(m.Nonce[:0], dAtA[iNdEx:postIndex]...)
			if m.Nonce == nil {
				m.Nonce = []byte{}
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Msg", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Msg == nil {
				m.Msg = &types.Any{}
			}
			if err := m.Msg.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
