// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: cronchain/signing_messages.proto

package cronchain

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type SignSmartContractExecute struct {
	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (m *SignSmartContractExecute) Reset()         { *m = SignSmartContractExecute{} }
func (m *SignSmartContractExecute) String() string { return proto.CompactTextString(m) }
func (*SignSmartContractExecute) ProtoMessage()    {}
func (*SignSmartContractExecute) Descriptor() ([]byte, []int) {
	return fileDescriptor_9096fd6c864aeffd, []int{0}
}
func (m *SignSmartContractExecute) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *SignSmartContractExecute) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_SignSmartContractExecute.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *SignSmartContractExecute) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignSmartContractExecute.Merge(m, src)
}
func (m *SignSmartContractExecute) XXX_Size() int {
	return m.Size()
}
func (m *SignSmartContractExecute) XXX_DiscardUnknown() {
	xxx_messageInfo_SignSmartContractExecute.DiscardUnknown(m)
}

var xxx_messageInfo_SignSmartContractExecute proto.InternalMessageInfo

func (m *SignSmartContractExecute) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func init() {
	proto.RegisterType((*SignSmartContractExecute)(nil), "volumefi.cronchain.concensus.SignSmartContractExecute")
}

func init() { proto.RegisterFile("cronchain/signing_messages.proto", fileDescriptor_9096fd6c864aeffd) }

var fileDescriptor_9096fd6c864aeffd = []byte{
	// 190 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x3c, 0xce, 0xb1, 0x4a, 0xc0, 0x30,
	0x10, 0x80, 0xe1, 0xa6, 0x88, 0x43, 0x07, 0x87, 0x4e, 0x1d, 0x24, 0x14, 0x27, 0x11, 0x4c, 0x06,
	0xdf, 0x40, 0x11, 0x77, 0xbb, 0xb9, 0x48, 0x7a, 0x8d, 0xe9, 0x81, 0xb9, 0x2b, 0xc9, 0x45, 0xf4,
	0x2d, 0x7c, 0x2c, 0xc7, 0x8e, 0x8e, 0xd2, 0xbe, 0x88, 0x20, 0xd8, 0xfd, 0x87, 0xef, 0x6f, 0x7a,
	0x48, 0x4c, 0x30, 0x3b, 0x24, 0x9b, 0x31, 0x10, 0x52, 0x78, 0x8e, 0x3e, 0x67, 0x17, 0x7c, 0x36,
	0x4b, 0x62, 0xe1, 0xf6, 0xfc, 0x8d, 0x5f, 0x4b, 0xf4, 0x2f, 0x68, 0x8e, 0xd4, 0x00, 0x13, 0x78,
	0xca, 0x25, 0x5f, 0x5c, 0x35, 0xdd, 0x80, 0x81, 0x86, 0xe8, 0x92, 0xdc, 0x31, 0x49, 0x72, 0x20,
	0xf7, 0xef, 0x1e, 0x8a, 0xf8, 0xf6, 0xac, 0xa9, 0x71, 0xea, 0x54, 0xaf, 0x2e, 0x4f, 0x1e, 0x6b,
	0x9c, 0x6e, 0x1f, 0xbe, 0x36, 0xad, 0xd6, 0x4d, 0xab, 0x9f, 0x4d, 0xab, 0xcf, 0x5d, 0x57, 0xeb,
	0xae, 0xab, 0xef, 0x5d, 0x57, 0x4f, 0xd7, 0x01, 0x65, 0x2e, 0xa3, 0x01, 0x8e, 0xf6, 0x9f, 0xb3,
	0xc0, 0x34, 0x15, 0x10, 0x4e, 0x56, 0x3e, 0x16, 0x9f, 0xed, 0xc1, 0x8f, 0xa7, 0x7f, 0x67, 0x37,
	0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x71, 0x3a, 0x8a, 0x27, 0xbd, 0x00, 0x00, 0x00,
}

func (m *SignSmartContractExecute) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SignSmartContractExecute) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *SignSmartContractExecute) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Id != 0 {
		i = encodeVarintSigningMessages(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintSigningMessages(dAtA []byte, offset int, v uint64) int {
	offset -= sovSigningMessages(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *SignSmartContractExecute) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovSigningMessages(uint64(m.Id))
	}
	return n
}

func sovSigningMessages(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozSigningMessages(x uint64) (n int) {
	return sovSigningMessages(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *SignSmartContractExecute) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSigningMessages
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SignSmartContractExecute: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SignSmartContractExecute: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSigningMessages
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipSigningMessages(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthSigningMessages
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipSigningMessages(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowSigningMessages
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowSigningMessages
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowSigningMessages
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthSigningMessages
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupSigningMessages
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthSigningMessages
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthSigningMessages        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowSigningMessages          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupSigningMessages = fmt.Errorf("proto: unexpected end of group")
)
